<a href="https://colab.research.google.com/github/sstanishk/tanishk-codeboosters-2026/blob/main/Day5/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
#import all required libraies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score

In [21]:
df = pd.read_csv('student_performance.csv')
print(f'Dataset loaded: {df.shape[0]} student, {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')
print(f'\nMissing values: {df.isnull().sum().values.sum()}')
print('\nFirst 5 rows: ')
df.head()

Dataset loaded: 30 student, 13 columns
Columns: ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

Missing values: 0

First 5 rows:

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [22]:
print(df["programming_score"].describe())

count    30.000000
mean     67.600000
std      21.041175
min      38.000000
25%      49.250000
50%      66.000000
75%      88.750000
max      97.000000
Name: programming_score, dtype: float64

In [23]:
#feature Engineering: encode categorical columns
df_ml =df.copy()
le_gender=LabelEncoder()
df_ml['gender_encoded']=le_gender.fit_transform(df_ml['gender'])
print(f'Gender encodeing:{dict(zip(le_gender.classes_,le_gender.transform(le_gender.classes_)))}')
le_dept=LabelEncoder()
df_ml['dept_encoded']=le_dept.fit_transform(df_ml['department'])
print(f'\nDepartment encoding:{dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))}')
print('\nNew columns added: gender_encoded,department_encoded')
df_ml[['gender','gender_encoded','department','dept_encoded']].head()

Gender encodeing:{'Female': np.int64(0), 'Male': np.int64(1)}

Department encoding:{'Civil': np.int64(0), 'Computer Science': np.int64(1), 'Electronics': np.int64(2), 'Mechanical': np.int64(3)}

New columns added: gender_encoded,department_encoded

   gender  gender_encoded        department  dept_encoded
0    Male               1  Computer Science             1
1  Female               0  Computer Science             1
2    Male               1       Electronics             2
3  Female               0        Mechanical             3
4    Male               1  Computer Science             1

In [28]:
feature_cols = [
    'math_score',
    'science_score',
    'english_score',
    'attendance_percentage',
    'gender_encoded',
    'dept_encoded'
]

x=df_ml[feature_cols]
y=df_ml['programming_score']

print(f'Feature matrix x shape: {x.shape} (students x features)')
print(f'Target vector y shape: {y.shape}  (one score per students)')
print(f'\nFeature columns: {feature_cols}')
print(f'Target column    : programming_score')
print(f'\nTarget range:  {y.min()} to {y.max()} (mean: {y.mean():.1f})')

Feature matrix x shape: (30, 6) (students x features)
Target vector y shape: (30,)  (one score per students)

Feature columns: ['math_score', 'science_score', 'english_score', 'attendance_percentage', 'gender_encoded', 'dept_encoded']
Target column    : programming_score

Target range:  38 to 97 (mean: 67.6)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(f'Total students   : {len(x)}')
print(f'Training_students: {len(X_train)} ({len(X_train)/len(x)*100:.0f}%)')
print(f'Testing_students : {len(X_test)} ({len(X_test)/len(x)*100:.0f}%)')
print(f'\nTraining target range:  {y_train.min()} - {y_train.max()} ')
print(f'Testing target range:   {y_test.min()} - {y_test.max()} ')

Total students   : 30
Training_students: 24 (80%)
Testing_students : 6 (20%)

Training target range:  38 - 96
Testing target range:   39 - 97

In [33]:
print('Total mean of training features:',X_train.values.mean())

Total mean of training features: 52.09722222222222

In [38]:
#Train model 1: Linear Regression
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)

#Evaluate
lr_mae=mean_absolute_error(y_test,lr_pred)
lr_rmse=np.sqrt(mean_squared_error(y_test,lr_pred))
lr_r2=r2_score(y_test,lr_pred)

print('=== Model 1: Linear Regression ===')
print(f'MAE: {lr_mae:.2f}')
print(f'RMSE: {lr_rmse:.2f}')
print(f'R2: {lr_r2:.2f}')
print()
print('Learned coefficents')
for feature, coef in zip(feature_cols, lr_model.coef_):
    print(f'{feature}: {coef:.2f}')
print(f'Intercept: {lr_model.intercept_:.4f}')

=== Model 1: Linear Regression ===
MAE: 9.37
RMSE: 11.47
R2: 0.74

Learned coefficents
math_score: 1.92
science_score: 0.91
english_score: 0.26
attendance_percentage: -1.49
gender_encoded: -0.80
dept_encoded: -0.47
Intercept: -39.8913

In [37]:
  #Train model 2: Decision Tree Regressor
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

dt_model = DecisionTreeRegressor()
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)

#Evaluate
dt_mae=mean_absolute_error(y_test,dt_pred)
dt_rmse=np.sqrt(mean_squared_error(y_test,dt_pred))
dt_r2=r2_score(y_test,dt_pred)

print('=== Model 2: Decision Tree Regressor ===')
print(f'MAE: {dt_mae:.2f}')
print(f'RMSE: {dt_rmse:.2f}')
print(f'R2: {dt_r2:.4f}')
print()

=== Model 2: Decision Tree Regressor ===
MAE: 10.00
RMSE: 14.18
R2: 0.5960

In [39]:
#Train model 3: Random Forest Regressor
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

rf_model = RandomForestRegressor(random_state=42) # Added random_state for reproducibility
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

#Evaluate
rf_mae=mean_absolute_error(y_test,rf_pred)
rf_rmse=np.sqrt(mean_squared_error(y_test,rf_pred))
rf_r2=r2_score(y_test,rf_pred)

print('=== Model 3: Random Forest Regressor ===')
print(f'MAE: {rf_mae:.2f}')
print(f'RMSE: {rf_rmse:.2f}')
print(f'R2: {rf_r2:.2f}')
print()

=== Model 3: Random Forest Regressor ===
MAE: 9.68
RMSE: 12.43
R2: 0.69